# Generated by Django 3.0.8 on 2020-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200702_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
