# Generated by Django 3.0.8 on 2020-07-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='title',
        ),
    ]
