# Generated by Django 3.0.8 on 2020-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
