# Generated by Django 3.0.8 on 2020-07-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200702_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_domain',
            new_name='domain',
        ),
    ]
