# Generated by Django 3.0.8 on 2020-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200702_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'building'), (2, 'failed'), (3, 'online')], default=0),
        ),
    ]
