# Generated by Django 3.0.8 on 2020-07-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_repository',
            field=models.TextField(max_length=255),
        ),
    ]
