# Generated by Django 3.0.8 on 2020-07-18 09:38

from django.db import migrations, models
import slippery.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200718_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='envfile',
            field=models.FileField(null=True, upload_to=slippery.projects.models.Project.envfile_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'building'), (2, 'failed'), (3, 'online')], default=0, editable=False),
        ),
    ]
