# Generated by Django 3.0.8 on 2020-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_status'),
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='project',
        ),
        migrations.AddField(
            model_name='database',
            name='project',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
