# Generated by Django 3.0.8 on 2020-07-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20200712_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='encrypted_password',
        ),
        migrations.RemoveField(
            model_name='database',
            name='encrypted_username',
        ),
        migrations.AddField(
            model_name='database',
            name='password',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='username',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
